var rulesLoc = "#server-rules";
var introLoc = "#introductions";
const FETCH_LIST = [" rummages in a closet, and fetches ",
    " dives into the ocean, and retrieves ",
    " hops into a dragon's hoard, and snatches ",
    "  ",
    "  ",
    "  ",
    "  ",
    "  ",
    "  ",
    "  ",
    "  ",
    " slides down the slippery slope, and offers a "];
const PILLOW_LIST = ["One of your characters receives an anonymous gift.",
    "Your character invites someone they don’t like over for dinner.",
    "A character is scared that someone will find out about something they did.",
    "Your character goes to the other side of town for a day.",
    "Two characters get into a heated argument about work.",
    "A character suddenly has to travel a long distance.",
    "One of your characters receives an anonymous gift.",
    "Your character invites someone they don’t like over for dinner.",
    "A character is scared that someone will find out about something they did.",
    "Your character goes to the other side of town for a day.",
    "Two characters get into a heated argument about work.",
    "A character suddenly has to travel a long distance."];
const WEATHER_LIST = ["It's sunny outside.  Oh no, wait, it's raining now.  Typical Melbourne weather!",
    "Do you really want to know whatthe weather is?  It's going to change in 5 minutes!",
    "Is that a full moon tonight?  Wow, how beautiful.",
    "Your character goes to the other side of town for a day.",
    "Two characters get into a heated argument about work.",
    "A character suddenly has to travel a long distance.",
    "Your character makes a new friend in an unexpected place.",
    "Your characters get dressed up.",
    "One of your characters isn’t who they claim to be.",
    "Your character is presented with a meal they don’t like.",
    "It's very wet out there.  Submarine stocks must be soaring!",
    "It's raining cats and dogs.  That explains the noise!"];